server:
  port: 8080
  servlet:
    contextPath: /

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: jt808-server
  jpa:
    show-sql: true
    format-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:file:${user.dir}/target/jt808
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 20000
      pool-name: hikari
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
  profiles:
    active: native

mybatis:
  type-aliases-package: com.zhoyq.server.jt808.entity
  mapper-locations: classpath:mapper/*.xml

jt808:
  use: mina
  protocol: tcp
  port: 10001
  processCount: 2
  corePoolSize: 1
  maximumPoolSize: 10
  # 单位毫秒
  keepAliveTime: 1000
  # 单位秒
  idleTime: 10
  idleCount: 6
  readBufferSize: 2048
  packageLength: 1024
  threadCorePoolSize: 1
  threadMaximumPoolSize: 10
  # 单位毫秒
  threadKeepAliveTime: 1000
  masterSize: 1
  slaveSize: 10
  tcpNoDelay: true
  keepAlive: true